name: Push workflow

on:
  push:
    tags:
    - invalid-tag

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker build
      if:
        github.event.deleted == false
      run: docker build -t peaceiris/actions-hugo .
    - name: Check Hugo version
      if: success()
      run: docker run peaceiris/actions-hugo:latest version
