name: 'Test'

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    # - name: Test script
    #   run: npm test

    - name: Build production
      run: npm run build


  test-prod:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        hugo-version: ['0.58.2']
        # hugo-version: [null, 'latest', '0.58.2']
        # extended: [null, false]
        extended: [null, true, false]

    steps:
    - uses: actions/checkout@v1

    - name: Test action
      uses: ./
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: ${{ matrix.extended }}

    - name: Dump
      run: hugo version
