name: 'Test'

on:
  push:
    branches:
      - 'migrate-javascript-action'

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    # - name: Test script
    #   run: npm test

    - name: Build production
      run: npm run build


  test-prod:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        hugo-version: [null, '0.58.2']
        # hugo-version: [null, 'latest', '0.58.2']
        extended: [null, true]
        # extended: [null, false, true]

    steps:
    - uses: actions/checkout@v1

    - name: Test action
      uses: ./
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: ${{ matrix.extended }}

    - name: Dump
      run: |
        ls -la ${HOME}
        hugo version
